#version 450

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly buffer BufScalar { float x[]; } bufscalar; // expects at least 1
layout(set = 0, binding = 1, std430) writeonly buffer BufOut { float y[]; } bufout;

layout(push_constant) uniform Push {
    uint n;
    float scale;
} pc;

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= pc.n) return;
    bufout.y[i] = bufscalar.x[0] * pc.scale;
}
